version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@fullstack3_high?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=ADMIN
      - spring.datasource.password=OracleCloud12321
    restart: always